### ISSUE TITLE
Alert KubernetesApiServerLatency Bugged

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#122]
Since the upgrade to the latest Prometheus this Alert is bugged. It reports the wrong metric and constantly alerts with false data.

https://github.com/coreos/prometheus-operator/issues/343
https://github.com/kubernetes/kubernetes/issues/44329

I propose we exclude `LIST` as well.

**Comment by auhlig** [comment]
https://github.com/sapcc/helm-charts/commit/7a8f98b656e0bb10bd3f1e3e4d3b1948ee926445
