### ISSUE TITLE
[Prometheus] Info Inhibitors

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#123]
Currently `severity=critical` inhibits `severity=warning` when the same `context` is set for alerts.

Add an additional inhibition rule: `severity=critical|warning` supresses `severity=info`

**Comment by auhlig** [comment]
done via https://github.com/sapcc/helm-charts/commit/a4ec8a26c72d4b12660b04077fae6f666625a8ac

**Comment by auhlig** [comment]
rolled out
