### ISSUE TITLE
Tuning of kube-monitoring

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#20]
- [x] PodRestart are to spammy as Warnings. Set to INFO Level
  - [x] Critical Alerts for when regional Prometheus are down are too aggressive. Relax timeframe
  - [x] Send Warnings to regional channels
  - [x] Critical Alerts should also send resolved notifications
  - [x] Docker Hang Alert is not sensitive enough

**Comment by auhlig** [comment]
Ticking `Critical Alerts should also send resolved notifications` as this already is configured [here](https://github.com/sapcc/helm-charts/blob/master/global/prometheus-alertmanager/templates/config.yaml#L68).

**Comment by auhlig** [comment]
closed via #84
