### ISSUE TITLE
Bugs in kube-monitoring 

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#21]
- [x] Remove AlertManager Releases/Trash from Regions. Should only be a single global instance.
 - [x] Node Exporter terminates as “Completed”. Needs to be restarted.
 - [x] Grouping for PodRestart Alerts doesn’t work properly. Too much spam during resolves. Remove or Fix.

**Comment by auhlig** [comment]
Ticking the 2nd: As described node exporter terminates with status complete. But the default restartPolicy of the daemonset is `Always` and it works as expected. Thus no further action is required, I guess.
