### ISSUE TITLE
[mariadb] Replace Global Master Password

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#2283]
https://github.com/sapcc/helm-charts/tree/master/common/mariadb

- Remove all references to `Values.global.master_password` 
- Prefer to not reference a global value. Instead require a password being passed to the chart

Prior Art:
https://github.com/sapcc/helm-charts/commit/a4c48f4160d81b1f3bbdb356f7526c431763ca4a

**Comment by galkindmitrii** [comment]
We don't use master_password for mariadb of mysql metrics. The services that use generated password are using own function in erb templates.

**Comment by BugRoger** [comment]
Would you please check the reference here:
https://github.com/sapcc/helm-charts/blob/master/common/mariadb/templates/_helpers.tpl#L23

If it's not being used, please remove those utility functions. It's not easy to figure out what happens if we remove the global `master_password`. Best case we have all references removed beforehand.

**Comment by galkindmitrii** [comment]
Will remove it, thanks.
