### ISSUE TITLE
[mysql_metrics] Replace Global Master Password 

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#2284]
https://github.com/sapcc/helm-charts/tree/master/common/mysql_metrics

- Remove all references to `Values.global.master_password` 
- Prefer to not reference a global value. Instead require a password being passed to the chart

Prior Art:
https://github.com/sapcc/helm-charts/commit/a4c48f4160d81b1f3bbdb356f7526c431763ca4a

**Comment by galkindmitrii** [comment]
We don't use master_password for mariadb of mysql metrics.

**Comment by BugRoger** [comment]
> We don't use master_password for mariadb of mysql metrics.
Perfect. I suppose, the reference here can be deleted then:
https://github.com/sapcc/helm-charts/blob/master/common/mysql_metrics/templates/_helpers.tpl#L24

**Comment by galkindmitrii** [comment]
Ah, that can be the case here: https://github.com/sapcc/helm-charts/commit/bf5570d444e86460d8a9c6cfc108948e79a41a30

**Comment by Carthaca** [comment]
It is fair that this task is assigned to me - I'm a heavy user of the master password algorithm ^^
