### ISSUE TITLE
[rabbitmq] Replace Global Master Password

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#2286]
https://github.com/sapcc/helm-charts/tree/master/common/rabbitmq

- Remove all references to `Values.global.master_password` 
- Prefer to not reference a global value. Instead require a password being passed to the chart

Prior Art:
https://github.com/sapcc/helm-charts/commit/a4c48f4160d81b1f3bbdb356f7526c431763ca4a

**Comment by BugRoger** [comment]
@Carthaca What is still missing? Can I help to move the topic along?

**Comment by Carthaca** [comment]
it is just work - please have a look at #2441
