### ISSUE TITLE
[nannies] Replace Global Master Password

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#2287]
https://github.com/sapcc/helm-charts/tree/master/openstack/nannies

- Remove all references to `Values.global.master_password` 
- Prefer to not reference a global value. Instead require a password being passed to the chart

Prior Art:
https://github.com/sapcc/helm-charts/commit/a4c48f4160d81b1f3bbdb356f7526c431763ca4a

**Comment by thgrs** [comment]
i'm on it already ... already commited and i'm in the process of rolling it out

**Comment by thgrs** [comment]
all done

**Comment by BugRoger** [comment]
Awesome. Thank you!
