### ISSUE TITLE
[utils/identity] Replace Global Master Password 

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#2293]
https://github.com/sapcc/helm-charts/blob/master/openstack/utils/templates/_hosts.tpl#L136

- Remove all references to `Values.global.master_password` 
- Prefer to not reference a global value. Instead require a password being passed to the chart

Prior Art:
https://github.com/sapcc/helm-charts/commit/a4c48f4160d81b1f3bbdb356f7526c431763ca4a

Take note that this utility function is being used in many other charts:

- `utils.password_for_fixed_user_and_host`
  - `identity.password_for_user`
    - https://github.com/sapcc/helm-charts/blob/master/openstack/barbican/templates/etc/_barbican.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/cinder/templates/etc/_cinder.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/glance/templates/etc/_glance-api.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/glance/templates/etc/_swift-store.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/ironic/templates/etc/_ironic.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/ironic/templates/etc/_ironic_inspector.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/ironic/templates/seed.yaml
    - https://github.com/sapcc/helm-charts/blob/master/openstack/neutron/templates/etc/_ironic_neutron_agent.ini.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/nova/templates/_console_deployment.yaml.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/nova/templates/etc/_nova-compute-ironic.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/nova/templates/etc/_nova.conf.tpl
    - https://github.com/sapcc/helm-charts/blob/master/openstack/nova/templates/seed.yaml
  - `svc.password_for_user_and_service`  
    - `oslo_messaging_rabbit_url` (unused)

Coordinated deployments might be required. :/

**Comment by joker-at-work** [comment]
I will remove autogenerated defaults in Nova and switch to explicit values. It just needs some more time as preparations are necessary. Once I got a PR up, I'll link it.

**Comment by joker-at-work** [comment]
WIP PR is up. https://github.com/sapcc/helm-charts/pull/2320

**Comment by BugRoger** [comment]
@rajivmucheli Thanks for taking a stab at this. You discarded the the big PR. What needs to happen for us to make progress here? Could you prepare smaller PRs and we ask the service owners to review?

**Comment by rajivmucheli** [comment]
https://github.com/sapcc/helm-charts/pull/2348

**Comment by rajivmucheli** [comment]
Current Status : Cinder, Neutron, Ironic PR's have been merged, I have taken care for Glance & Barbican. Nova Service will be taken care by Johannes(on vacation). Once all service have deployed the commit across regions, i will bump/remove identity.password_for_user from utils charts.

**Comment by BugRoger** [comment]
Thank you @rajivmucheli
