### ISSUE TITLE
Update Node Exporter Specs for Diskstats

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#23]
Implement this change in the node-exorter daemonset. Maybe the disk stats will be more usable then...

https://github.com/prometheus/node_exporter/commit/21173e21f06d14af1bdbdfe101a3de7bce168f80

Bonus Points: Remove the `/host` prefix in an aggregation rule.

**Comment by auhlig** [comment]
Done via https://github.com/sapcc/helm-charts/pull/84.
