### ISSUE TITLE
Not able to deploy on the local k8s cluster

### ISSUE THREAD

**Issue by QuesadaMarvin** [sapcc/helm-charts#2386]
Hi team. I am trying to deploy openstack services(swift for the first time) on my local k8s cluster. When I run helm install, it returns the following error message.
```
Error: execution error at (swift/templates/workers-daemonset.yaml:33:54): This release should be installed by the deployment pipeline!
```
It seems likely the values.yaml file includes some hardcoded constants which will be replaced in CICD pipeline.
How can I use these helm charts? Where are the container images for them?

**Comment by notandy** [comment]
Hi @QuesadaMarvin, this repository is part of the open source initiative of the Converged Cloud, which is a heavily customised OpenStack installation loosely based on the [Openstack-Helm](https://opendev.org/openstack/openstack-helm) project. Container images, Dockerfiles, Pipeline definitions and other secrets are therefor proprietary. We don't provide any support for using the helm-charts, but rather Open Sourcing parts of it for public exchange and learning purposes. Feel free to read and re-purpose the helm-chart definitions for your own project, but don't expect them to be usable out of the box.

As said, probably you want to have a look at Openstack-Helm which has a proper documentation and works with vanilla OpenStack containers.

Best,
Andy

**Comment by QuesadaMarvin** [comment]
Hi team.
I have been operating openstack on k8s cluster deployed by Openstack-helm project. (https://opendev.org/openstack/openstack-helm).
This project includes several main services of openstack and all are packaged by helm charts.
Unfortunately, it does not provide swift yet. So I am trying to build swift container image and package the helm chart. In Openstack-helm, all container images are created by loci project(https://opendev.org/openstack/loci) but I don't think I need to build in that way.
I am interested in your containerization method and want to discuss the details. I am willing to contribute also.

Regards.
