### ISSUE TITLE
Increase Severity for NodeNotReady Alerts

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#28]
The `NodeNotReady` alert needs to be treated with urgency.

It is indicative of the node being stuck with a hanging kernel. This leads to problems if locks are still being held for persistent applications. Upon rescheduling those applications will not recover and stay in `CrashLoopBackoff` until manual intervention. Which could lead to severe outage if critical databases, like Keystone, are affected.

Increase the severity of the alert to `critical`. Update Playbook.

**Comment by auhlig** [comment]
Increased severity, added playbook, link, etc.
