### ISSUE TITLE
Proactively Detect Kubelet Problems - Go-Routine Leaks 

### ISSUE THREAD

**Issue by BugRoger** [sapcc/helm-charts#29]
Recently we have been seeing some instances of "unresponsive" Kubelets. The symptoms are Pods being scheduled but not starting and related problems. Our current alerting doesn't detect this. This is because the Kubelet is actually still running and responsive. 

My suspicion is that it gets stuck in some endless retry loop or the like. A restart fixes the problem. Pending finding out the actual root cause and fixing the bug, we need to have an alert so we can proactively fix the problem.

One possible way to detect this would be to find abnormal spikes in the number of Go Routines the kubelet is creating. 

This query shows a recent incident.
https://prometheus.staging.cloud.sap/graph?g0.range_input=1w&g0.expr=go_goroutines%7Bjob%3D%22kube-system%2Fkubelet%22%7D&g0.tab=0

Normal on eu-de-1:
![image](https://cloud.githubusercontent.com/assets/147369/22058249/9519c30a-dd68-11e6-8623-a68749e3f07c.png)

Abnormal on staging:
![image](https://cloud.githubusercontent.com/assets/147369/22058287/b3f3893c-dd68-11e6-926c-c3e65f771ee6.png)

Implement an alert when GoRoutines are spiking.

**Comment by BugRoger** [comment]
There's also a nice spike in memory usage, that could be an indicator of a problem:
![image](https://cloud.githubusercontent.com/assets/147369/22058664/08fe85c0-dd6a-11e6-97f3-9e48fd2e72c1.png)

https://prometheus.staging.cloud.sap/graph?g0.range_input=1w&g0.expr=go_memstats_alloc_bytes%7Bjob%3D%22kube-system%2Fkubelet%22%7D&g0.tab=0

**Comment by jobrs** [comment]
+1

**Comment by auhlig** [comment]
Done via #84
