### ISSUE TITLE
prometheus-global retention time

### ISSUE THREAD

**Issue by majewsky** [sapcc/helm-charts#61]
```
$ grep retention global/prometheus/values.yaml
2:retention: 168h0m0s
```

@BugRoger @auhlig I recall this being a lot more (something like 90 days or so). Was there a copy-paste error, or did we scale it down over storage space concerns?

**Comment by auhlig** [comment]
As discussed via IM this should be 90d, at least in theory. 
Shouldn't do much harm to try and rolling back if necessary.
