### ISSUE TITLE
how can this pattern be used to deploy multiple instances of same chart

### ISSUE THREAD

**Issue by Dhananjay-J-P** [sapcc/helm-charts#854]
I want 4 instances of mysql chart for separate applications, how can I achieve this using SAP converged pattern? 

in Deis workflow method, in requirements.yaml I can launch 4 instances of a chart using alias, is there similar way available.

**Comment by notque** [comment]
Yes, you can alias in requirements.

**Comment by notque** [comment]
This is quite old, but yes, you can launch multiple instances using an alias in requirements.yaml as you stated. Closing this.
